[package]
name = "char-from-utf8"
version = "0.1.0"
edition = "2021"
authors =["xmh0511 <970252187@qq.com>" ]
repository = "https://github.com/xmh0511/char-from-utf8"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
